config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'pages#home'

  resources :categories
  resources :products
  resources :order_items

  get 'menu',     to: 'menu#index'
  get 'search',   to: 'menu#search'
  get 'cart',     to: 'cart#show'
  
  get 'info',     to: 'pages#info'
  get 'catering', to: 'pages#catering'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_items

  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.unit_price * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :product
  belongs_to :order

  before_save :set_unit_price
  before_save :set_total

  def unit_price

    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total
    return unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end

end

app/models/product.rb
class Product < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :category
  has_many :order_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include ApplicationHelper

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :avatar_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :avatar_cache])
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    @order_items = current_order.order_items
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: %i[ show edit update destroy ]

  def index
    @categories = Category.all
  end

  def show; end
  def edit; end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:heading, :body, :display)
  end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController

  before_action :set_cats

  def index
    @page = 'menu'
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def search
    query = params[:search]

    results = Product.where('name LIKE ?', "%#{query}%")

    if params[:filter] == 'Select Filter'
      @products == results
    else
      symbol = params[:filter].gsub(/ /, '_').downcase!.to_sym

      @products = results.where(symbol => true)
    end
  end

  private

  def set_cats
    @cats = Category.all.where(display: true)
  end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  before_action :set_order

  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @page = 'home'
  end

  def catering
    @page = 'catering'
  end

  def info
    @page = 'info'
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def show; end
  def edit; end

  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @product.category = Category.find(params[:product][:category_id])

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :price,
      :dairy_free,
      :gluten_free,
      :kosher,
      :peanut_free,
      :vegan,
      :vegetarian,
      :available,
      :catering,
      :featured,
      :image,
      :image_cache,
      :category_id
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end

  def current_order
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def product_image product
    image_path = product.image.present? ? product.image.url : 'product.jpg'
    image_tag(image_path, class: 'img-fluid')
  end

end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>

  <h3><%= item.product.name %></h3>
  <h3><%= item.product.price %></h3>

  <%= form_with model: item do |f| %>
    <%= f.hidden_field :product_id, value: item.product.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i %>
    <%= f.submit 'Update Cart', class: 'btn btn-sm btn-primary' %>
    <%= link_to 'Remove Items', item, method: :delete, remote: true, class: 'btn btn-sm btn-danger' %>
  <% end %>

  <h2>Subtotal: <%= item.total %></h2>

<% end %>

<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
  <%= render 'cart_items' %>
</div>

<hr>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: 'btn btn-sm btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container mt-5 mb-5">
  <h5 class="mb-5">Editing Category</h5>

  <%= render 'form', category: @category %>

  <%= link_to 'Show', @category %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<h5 class="mt-5 mb-5">Categories list</h5>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Heading</th>
      <th>Body</th>
      <th>Display</th>
      <th colspan="3">Controlls</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><small><%= category.heading %></small></td>
        <td><small><%= category.body %></small></td>
        <td><small><%= category.display %></small></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<div class="container mb-5">
  <h5 class="mt-5 mb-5">New Category</h5>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container">

  <h3 class="mt-5 mb-5">
    Category params
  </h3>

  <p>
    <strong>Heading:</strong>
    <%= @category.heading %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @category.body %>
  </p>

  <p>
    <strong>Display:</strong>
    <%= @category.display %>
  </p>

  <%= link_to 'Edit', edit_category_path(@category) %> |
  <%= link_to 'Back', categories_path %>
</div>

app/views/layouts/_links.html.erb
<div class="col-2">
  <h5 class="link-container">
    <%= link_to 'Home', root_path, class: "link #{@page == 'home' ? 'active' : ''}" %>
  </h5>

  <h5 class="link-container">
    <%= link_to 'Menu', menu_path, class: "link #{@page == 'menu' ? 'active' : ''}" %>
  </h5>

  <h5 class="link-container">
    <%= link_to 'Catering', catering_path, class: "link #{@page == 'catering' ? 'active' : ''}" %>
  </h5>

  <h5 class="link-container">
    <%= link_to 'More Info', info_path, class: "link #{@page == 'info' ? 'active' : ''}" %>
  </h5>

  <h5 class="link-container">
    <%= link_to 'Castomer Reviews', '', class: "link #{@page == 'reviews' ? 'active' : ''}" %>
  </h5>

  <% if current_user.present? && current_user.admin? %>
    <h4 class="link-container">
      <%= link_to 'Product List', products_path %>
    </h4>

    <h4 class="link-container">
      <%= link_to 'Categories List', categories_path %>
    </h4>
  <% end %>

</div>

app/views/layouts/_title.html.erb
<div class="title-card sticky-top">
  <h1 class="title-text">
    Gor's Foods
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafe App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
  </head>

  <body>

    <% cache do %>
      <div class="<%= @page %>-page">
        <div class="row page-container">
          <%= toastr_flash %>

          <%= render 'layouts/links' %>

          <div class="col-8">
            <%= render 'layouts/title' %>

            <%= yield %>
          </div>

          <div class="col-1"></div>

          <div class="col-1 p-2">
            <% if user_signed_in? %>
              <h6><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></h6>
              <%= link_to edit_user_registration_path do %>
                <h6 class="text-white text-decoration-none">
                  <%= current_user.username %>
                </h6>
              <% end %>
            <% else %>
              <h6><%= link_to 'Sign in', new_user_session_path %></h6>
              <h6><%= link_to 'Sign up', new_user_registration_path %></h6>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  </body>
</html>

app/views/menu/_products.html.erb
<div class="row">
  <% @cats.each do |cat| %>

    <% if cat.products.first.present? %>
      <%= product_image cat.products.first %>
    <% end %>

    <div class="col-12 mt-3">
      <h1 class="text-muted" style="text-align:center;"><%= cat.heading %></h1>
      <hr>
    </div>

    <% @products.each do |product| %>

      <% if product.category == cat %>
        <div class="col-4 mb-5">

          <h5><%= product.name %></h5>

          <div class="card-text">
            <div class="mt-3">

              <small class="float-left text-muted">Price</small>

              <p class="float-right text-muted mb-0">
                <strong>
                  $<%= product.price %> <%= '| Available for catering' if product.catering? %>
                </strong>
              </p>
            </div>
          </div>

          <div>
            <div class="accordion" id="accordionExample">

              <button
                class="btn btn-link btn-block text-left text-muted text-decoration-none text-dark pl-0 pt-0 pb-2"
                type="button"
                data-toggle="collapse"
                data-target="#<%= product.name %>-description"
                aria-expanded="true"
                aria-controls="collapseOne">
                <small>
                  View  Description
                </small>
              </button>

              <div
                id="<%= product.name %>-description"
                class="collapse mb-2"
                aria-labelledby="headingOne"
                data-parent="#accordionExample">
                <div class="card-body bg-light mt-2">
                  <small class="text-muted">
                    <%= product.description %>
                  </small>
                </div>
              </div>

            </div>
          </div>

          <%= form_with model: @order_item do |f| %>

            <%= f.hidden_field :product_id, value: product.id %>
            <div class="input-group input-group-sm mt-4">
              <small class="mt-2">Count</small>
              <%= f.number_field :quantity, value: 1, min: 1, class: 'form-control', id: 'product-count-field' %>
              <div class="input-group-append">
                <%= f.submit "Add To Cart", class: "btn btn-sm btn-outline-primary" %>
                <%= button_to "Buy now", product, class: "btn btn-sm btn-outline-success" %>
                <%= button_to "Details", product, method: :get, class: "btn btn-sm btn-outline-secondary" %>
              </div>
            </div>
          <% end %>

        </div>
      <% end %>
    <% end %>

  <% end %>
</div>

app/views/menu/_search.js.erb
$('#menu-products-container').html('<%= j render "menu/products" %>');

app/views/menu/index.html.erb
<div class="menu-container">
  <div class="row">
    <div class="col-12">

      <%= form_tag(search_path, method: 'get', remote: true) do %>
        <div class="input-group mb-5">

          <div class="col-8" style="padding:0">
            <%= text_field_tag :search, '', class: 'form-control', placeholder: 'Search', onkeydown: 'clickSubmit();' %>
          </div>

          <div class="col-4" style="padding:0"">
            <%= select_tag 'filter', options_for_select([
              'Select Filter',
              'Dairy Free',
              'Gluten Free',
              'Kosher',
              'Penaut Free',
              'Vegan',
              'Vegetarian'
            ]), class: 'custom-select', onchange: 'clickSubmit();' %>

            <%= submit_tag 'Search', class: 'btn btn-dark', id: 'search_submit', style: 'display:none' %>
          </div>

        </div>
      <% end %>

    </div>
  </div>

  <div id="menu-products-container">
    <%= render 'menu/products' %>
  </div>
</div>

<script type="text/javascript">
  function clickSubmit() {
    $('#search_submit').trigger('click');
  }
</script>

app/views/order_items/create.js.erb
$('#cart').html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$('#cart').html("<%= j render 'cart/cart' %>");
$('#cart_item').html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$('#cart').html("<%= j render 'cart/cart' %>");
$('#cart_item').html("<%= j render 'cart/cart_items' %>");

app/views/pages/home.html.erb
<div class="col-8">

</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label 'Product Image' %>
    <div class="custom-file">
      <%= form.label 'Choose file', class: 'custom-file-label' %>
      <%= form.file_field :image, type: 'file', class: 'custom-file-input' %>
      <%= form.hidden_field :image_cache %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :category %>
    <%= form.select(:category_id, options_from_collection_for_select(Category.all, :id, :heading, (@product.category.id if @product.category.present?)), {}, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :dairy_free %>
    <%= form.check_box :dairy_free %>
  </div>

  <div class="form-group">
    <%= form.label :gluten_free %>
    <%= form.check_box :gluten_free %>
  </div>

  <div class="form-group">
    <%= form.label :kosher %>
    <%= form.check_box :kosher %>
  </div>

  <div class="form-group">
    <%= form.label :peanut_free %>
    <%= form.check_box :peanut_free %>
  </div>

  <div class="form-group">
    <%= form.label :vegan %>
    <%= form.check_box :vegan %>
  </div>

  <div class="form-group">
    <%= form.label :vegetarian %>
    <%= form.check_box :vegetarian %>
  </div>

  <div class="form-group">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="form-group">
    <%= form.label :catering %>
    <%= form.check_box :catering %>
  </div>

  <div class="form-group">
    <%= form.label :featured %>
    <%= form.check_box :featured %>
  </div>

  <div class="form-group">
    <%= form.submit class: 'btn btn-sm btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container mt-5 mb-5">
  <h5 class="mb-5">Editing Product</h5>

  <%= render 'form', product: @product %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<h5 class="mt-5 mb-5">Products list</h5>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Price</th>
      <th>Cat</th>
      <th>Image</th>
      <th>Dairy free</th>
      <th>Gluten free</th>
      <th>Kosher</th>
      <th>Peanut free</th>
      <th>Vegan</th>
      <th>Vegetarian</th>
      <th>Available</th>
      <th>Catering</th>
      <th>Featured</th>
      <th colspan="3">Controlls</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><small><%= product.id %></small></td>
        <td><small><%= product.name %></small></td>
        <td><small><%= product.price %></small></td>
        <td><small><%= product.category.heading %></small></td>
        <td><small><%= product.image.identifier %></small></td>
        <td><small><%= product.dairy_free %></small></td>
        <td><small><%= product.gluten_free %></small></td>
        <td><small><%= product.kosher %></small></td>
        <td><small><%= product.peanut_free %></small></td>
        <td><small><%= product.vegan %></small></td>
        <td><small><%= product.vegetarian %></small></td>
        <td><small><%= product.available %></small></td>
        <td><small><%= product.catering %></small></td>
        <td><small><%= product.featured %></small></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<div class="container mb-5">
  <h5 class="mt-5 mb-5">New Product</h5>

  <%= render 'form', product: @product %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container">

  <h3 class="mt-5 mb-5 display-3">
    <%= @product.category.heading %>
  </h3>

  <h4 class="mb-3">
    <%= @product.name %>
  </h4>

  <div>
    <div class="card p-3 mt-3 mb-3">
      <small class="mb-3">Description:</small>
      <%= @product.description %>
    </div>
  </div>
  <hr>

  <p>
    <small>Product Image:</small>
    <%= @product.image.identifier %>
  </p>
  <hr>

  <p>
    <small>Price:</small>
    <%= @product.price %>
  </p>
  <hr>

  <p>
    <small>Dairy free:</small>
    <%= @product.dairy_free %>
  </p>
  <hr>

  <p>
    <small>Gluten free:</small>
    <%= @product.gluten_free %>
  </p>
  <hr>

  <p>
    <small>Kosher:</small>
    <%= @product.kosher %>
  </p>
  <hr>

  <p>
    <small>Peanut free:</small>
    <%= @product.peanut_free %>
  </p>
  <hr>

  <p>
    <small>Vegan:</small>
    <%= @product.vegan %>
  </p>
  <hr>

  <p>
    <small>Vegetarian:</small>
    <%= @product.vegetarian %>
  </p>
  <hr>

  <p>
    <small>Available:</small>
    <%= @product.available %>
  </p>
  <hr>

  <p>
    <small>Catering:</small>
    <%= @product.catering %>
  </p>
  <hr>

  <p>
    <small>Featured:</small>
    <%= @product.featured %>
  </p>
  <hr>

  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
  <hr>
</div>